version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - default

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: taxi
      POSTGRES_PASSWORD: taxi123
      POSTGRES_DB: taxi_rides

  spark:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_SUBMIT_OPTIONS=--packages org.postgresql:postgresql:42.2.18
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - .:/workspace
    networks:
      - default

  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
      
  producer:
    build:
      context: .
      dockerfile: ingestion/Dockerfile
    depends_on:
      - kafka
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - default

networks:
  default:


